name: stale
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions: read-all
jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          days-before-issue-stale: 90
          days-before-issue-close: 14
          stale-issue-label: stale
          stale-issue-message: >
            This issue has been inactive for 90 days. It will be closed in 14 days if no further activity occurs.
            Comment to keep it open or add a `needs/triage` label.
          close-issue-message: >
            Closed due to inactivity. Reopen if this is still relevant.
          days-before-pr-stale: 60
          days-before-pr-close: 14
          stale-pr-label: stale
          stale-pr-message: >
            This PR has been inactive for 60 days. It will be closed in 14 days if no further activity occurs.
          exempt-issue-labels: "blocked,help wanted,good first issue,area/rfc"
          exempt-pr-labels: "blocked,help wanted"
          operations-per-run: 100
